In [17]:
import pandas as pd

In [35]:
dados = pd.read_excel('C:/Users/thelsandro/Documents/tech/_Desafio_2_relatorio.xlsx', sheet_name = "Dados - Questão 1")

In [37]:
dados.head(100)

,num_compra,usuario,nome,Tipo de Mercadoria,Filial,data_compra,valor_compra,Imposto,CPF NA NOTA?
0,24937847,295,ANDERSON,SPLIT 8501 À 10000,Loja Autazes,2020-04-06 12:25:12.666,2582.400,116.20800,Sim
1,23600787,331,RAIMUNDO,SPLIT INV 8501À10000,Loja Manicor é,2020-04-06 14:03:54.682,1919.280,86.36760,Sim
2,24298956,370,ROSILANE,SPLIT ACIMA DE 30000,Loja Manicor é,2020-04-06 14:35:14.125,10121.040,455.44680,Sim
3,23802765,460,SANDRA,SPLIT 10001 À 18000,Loja Manicor é,2020-04-06 14:59:19.759,11724.000,527.58000,Sim
4,22559356,538,JAMERSON,SPLIT 18001 À 30000,Loja Manicor é,2020-04-06 15:32:43.879,1157.280,52.07760,Sim
...,...,...,...,...,...,...,...,...,...
95,24765932,28069,DANIEL,MERGULHO,Loja Manicor é,2020-04-13 09:00:11.077,26.432,1.18944,Na~o
96,24313851,28107,ILCIA,REL MASC AUTOMÁTICO,Loja Lábrea,2020-04-13 09:48:28.359,38.600,1.73700,Na~o
97,24311018,28181,ANA,RELÓGIO MASC ANALÓG,Loja Lábrea,2020-04-13 09:52:08.295,3.560,0.16020,Na~o
98,22476029,28211,JULIANA,RELÓGIO FEM ANALÓG,Loja Lábrea,2020-04-13 10:06:03.948,88.916,4.00122,Na~o
99,24660686,28300,GABRIEL,RELÓGIO PULSO INF-JU,Loja Lábrea,2020-04-13 10:28:02.177,125.444,5.64498,Na~o