In [1]:
import pandas as pd
arq = pd.read_csv('C:/Users/thelsandro/Documents/GitHub/codigos_python/machine/wine_dataset.csv')

In [2]:
arq.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [3]:
arq['style'] = arq['style'].replace('red',0)

In [4]:
arq['style'] = arq['style'].replace('white',1)

In [11]:
arq

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,1
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,1
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,1
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,1
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,1

In [13]:
y = arq['style']
x = arq.drop('style', axis=1)

In [16]:
arq.shape

(6497, 13)

In [19]:
from sklearn.model_selection import train_test_split
x_treino, x_teste,y_treino,y_teste = train_test_split(x,y,test_size=0.3)

In [20]:
x_treino.shape

(4547, 12)

In [21]:
from sklearn.ensemble import ExtraTreesClassifier

model = ExtraTreesClassifier()
model.fit(x_treino,y_treino)

result = model.score(x_teste,y_teste)
print('Acurácia', result)

Acurácia 0.9974358974358974

In [22]:
y_teste[400:403]

4109    1
2741    1
4507    1
Name: style, dtype: int64

In [23]:
x_teste[400:403]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
4109,6.2,0.28,0.45,7.5,0.045,46.0,203.0,0.99573,3.26,0.46,9.2,6
2741,9.2,0.28,0.46,3.2,0.058,39.0,133.0,0.99600,3.14,0.58,9.5,5
4507,6.2,0.20,0.31,1.0,0.031,22.0,73.0,0.99035,3.24,0.52,11.3,6

In [40]:
arq.loc[2741]

fixed_acidity             9.200
volatile_acidity          0.280
citric_acid               0.460
residual_sugar            3.200
chlorides                 0.058
free_sulfur_dioxide      39.000
total_sulfur_dioxide    133.000
density                   0.996
pH                        3.140
sulphates                 0.580
alcohol                   9.500
quality                   5.000
style                     1.000
Name: 2741, dtype: float64